name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          macos-latest,
          windows-2022
        ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.1+12'

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build image no installer
        run: ./gradlew --info jpackage -PskipInstaller=true

      - name: Upload Linux dist as an artifact
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          name: dist-linux
          path: build/dist

      - name: Upload Mac dist as an artifact
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(matrix.os, 'mac') }}
        with:
          name: dist-mac
          path: build/dist

      - name: Upload Windows dist as an artifact
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          name: dist-windows
          path: build/dist
